"use client";

import { useEffect, useRef, useState } from "react";

type PagefindResult = {
  id: string;
  data: () => Promise<{
    url: string;
    excerpt: string;
    meta: { title?: string };
  }>;
};

type Pagefind = {
  search: (q: string) => Promise<{ results: PagefindResult[] }>;
};

type Loaded = { title: string; url: string; excerpt: string };

declare global {
  interface Window {
    __pagefind?: Pagefind;
  }
}

async function loadPagefind(): Promise<Pagefind | null> {
  if (typeof window === "undefined") return null;
  if (window.__pagefind) return window.__pagefind;
  try {
    // Pagefind's runtime is generated by the postbuild script and lives at
    // /pagefind/pagefind.js — it doesn't exist at Turbopack/Webpack build time,
    // so we have to load it at runtime. We wrap the dynamic import in `new
    // Function` to keep both bundlers from trying to statically resolve the URL
    // (the webpackIgnore / @vite-ignore comments don't help with Turbopack).
    const importer = new Function(
      "u",
      "return import(u)"
    ) as (u: string) => Promise<unknown>;
    const mod = (await importer("/pagefind/pagefind.js")) as Pagefind;
    window.__pagefind = mod;
    return mod;
  } catch (err) {
    console.error("[search] failed to load /pagefind/pagefind.js", err);
    return null;
  }
}

export function SearchClient() {
  const [q, setQ] = useState("");
  const [results, setResults] = useState<Loaded[]>([]);
  const [status, setStatus] = useState<"idle" | "ready" | "missing" | "error">(
    "idle"
  );
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
    loadPagefind().then((pf) => setStatus(pf ? "ready" : "missing"));
  }, []);

  useEffect(() => {
    let cancelled = false;
    if (!q.trim()) {
      setResults([]);
      return;
    }
    if (status !== "ready") return;
    (async () => {
      const pf = await loadPagefind();
      if (!pf) return;
      try {
        const search = await pf.search(q);
        const top = await Promise.all(
          search.results.slice(0, 20).map(async (r) => {
            const data = await r.data();
            return {
              title: data.meta.title ?? data.url,
              url: data.url,
              excerpt: data.excerpt,
            };
          })
        );
        if (!cancelled) setResults(top);
      } catch {
        if (!cancelled) setStatus("error");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [q, status]);

  return (
    <div>
      <input
        ref={inputRef}
        value={q}
        onChange={(e) => setQ(e.target.value)}
        placeholder="What are you looking for?"
        type="search"
        aria-label="Search query"
        style={{
          width: "100%",
          padding: "14px 18px",
          fontSize: 16,
          fontFamily: "var(--font-sans)",
          border: "1px solid var(--border)",
          borderRadius: 12,
          background: "var(--surface)",
          color: "var(--page-fg)",
        }}
      />

      {status === "missing" ? (
        <p
          style={{
            marginTop: 24,
            font: "400 14px/22px var(--font-sans)",
            color: "var(--page-fg-soft)",
          }}
        >
          Search index not loaded. If you&rsquo;re running the dev server, run{" "}
          <code className="code-chip">npm run build</code> once to generate the
          Pagefind index — the postbuild step mirrors it to{" "}
          <code className="code-chip">public/pagefind/</code> so dev mode picks
          it up too.
        </p>
      ) : null}

      {status === "error" ? (
        <p
          style={{
            marginTop: 24,
            font: "400 14px/22px var(--font-sans)",
            color: "var(--state-error)",
          }}
        >
          Search failed to load. Refresh the page to try again.
        </p>
      ) : null}

      <ul style={{ listStyle: "none", padding: 0, marginTop: 32 }}>
        {results.map((r) => (
          <li key={r.url} style={{ marginBottom: 16 }}>
            <a
              href={r.url}
              style={{
                display: "block",
                padding: 16,
                border: "1px solid var(--border)",
                borderRadius: 12,
                background: "var(--surface)",
                textDecoration: "none",
                color: "inherit",
              }}
            >
              <div
                style={{
                  font: "600 16px/22px var(--font-display)",
                  color: "var(--page-fg)",
                  marginBottom: 4,
                }}
              >
                {r.title}
              </div>
              <div
                style={{
                  font: "400 13px/20px var(--font-sans)",
                  color: "var(--page-fg-muted)",
                }}
                dangerouslySetInnerHTML={{ __html: r.excerpt }}
              />
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}
